config/routes.rb
Rails.application.routes.draw do
  get 'design', to: 'pages#design', as: :design
  get 'flats', to: 'flats#index', as: :flats
  get 'flats/:id', to: 'flats#show', as: :flat
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
    before_action :get_flats, only: [:index, :show]

    # def new
    #     generate_letters
    # end

    # def score
    #     letters = params[:letters]
    # end

    def index
        # render 'flats/index.html.erb'
    end

    def show
        # get specific flat using id
        id = params[:id].to_i
        @flat = @flats.find{ |flat| flat['id'] == id }
        next_flat_index = @flats.index(@flat) + 1
        @next_flat = @flats[next_flat_index]
    end

    private

    # def generate_letters
    #     # CALL API AND RETURN LETTERS
    #     @letters = 'uhbjhvkjhv'
    # end

    def get_flats
        url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
        response = URI.open(url).read
        @flats = JSON.parse(response)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def design
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/flats/index.html.erb
<div class="mx-auto max-w-3xl p-4 pt-8">
	<h1 class="font-bold text-4xl mb-4">Flats</h1>
	<!-- Grid -->
	<div class="grid gap-6 grid-cols-1 sm:grid-cols-2 md:grid-cols-3">
		<!-- Flat card -->
		<%# Todo... display all flats %>
        <% @flats.each do |flat| %>
            <%= link_to flat_path(flat["id"]) do %>
                <div class='aspect-w-1 aspect-h-1 bg-white mb-1 block group overflow-hidden rounded mb-2'>
                    <%= image_tag "#{flat['imageUrl']}", class:"h-full w-full object-cover object-center transform-gpu scale-100 group-hover:scale-105 transition-transform duration-300 ease-out" %>
                </div>
                <h4 class="leading-none font-bold mb-1"><%= flat["name"] %></h4>
                <p class="text-sm text-gray-500"><%= flat["price"] %> <%= flat["priceCurrency"] %></p>
            <% end %>
        <% end %>
	</div>
</div>

app/views/flats/show.html.erb
<div class="mx-auto max-w-3xl p-4 pt-8">
    <%# link_to 'link text', 'path/to/page' %>
    <%= link_to flats_path, class:'p-2 h-10 w-10 bg-gray-200 rounded-full flex items-center justify-center' do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="inline h-5 w-5" width="44" height="44" viewBox="0 0 24 24" stroke-width="1.5" stroke="#2c3e50" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
            <path d="M20 15h-8v3.586a1 1 0 0 1 -1.707 .707l-6.586 -6.586a1 1 0 0 1 0 -1.414l6.586 -6.586a1 1 0 0 1 1.707 .707v3.586h8a1 1 0 0 1 1 1v4a1 1 0 0 1 -1 1z" />
        </svg>
    <% end %>
    <div class='aspect-video bg-white mb-1 block group overflow-hidden rounded mb-4'>
        <%= image_tag "#{@flat['imageUrl']}", class:"h-full w-full object-cover object-center" %>
    </div>
	<h1 class="font-bold text-4xl mb-2"><%= @flat["name"] %></h1>
    <p class="text-gray-500"><%= @flat["price"] %> <%= @flat["priceCurrency"] %></p>
    <%= link_to flat_path(@next_flat["id"]), class:'p-2 h-10 w-10 bg-gray-200 rounded-full flex items-center justify-center transform rotate-180' do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="inline h-5 w-5" width="44" height="44" viewBox="0 0 24 24" stroke-width="1.5" stroke="#2c3e50" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
            <path d="M20 15h-8v3.586a1 1 0 0 1 -1.707 .707l-6.586 -6.586a1 1 0 0 1 0 -1.414l6.586 -6.586a1 1 0 0 1 1.707 .707v3.586h8a1 1 0 0 1 1 1v4a1 1 0 0 1 -1 1z" />
        </svg>
    <% end %>
</div>

<% if false %>
    <form>
        <input name="letters" value="<%= @letters %>">
    </form>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbStatic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://cdn.tailwindcss.com"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/design.html.erb
<div class="mx-auto max-w-3xl p-4 pt-8">
	<h1 class="font-bold text-4xl mb-4">Flats</h1>
	<!-- Grid -->
	<div class="grid grid-gap-4 grid-cols-1 sm:grid-cols-2 md:grid-cols-3">
		<!-- Flat card -->
		<div>
			<%= link_to '#', class: 'aspect-w-1 aspect-h-1 bg-white mb-1 block group overflow-hidden rounded' do %>
				<%= image_tag 'https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/images/flat2.jpg', class:"h-full w-full object-cover object-center transform-gpu scale-100 group-hover:scale-105 transition-transform duration-300 ease-out" %>
			<% end %>
		</div>
	</div>
</div>